### ISSUE TITLE
Question about soul_map.txt

### ISSUE THREAD

**Issue by progressionnetwork** [jnastarot/soul_eater#1]
How did you generate such file?

**Comment by jnastarot** [comment]
by my hands for now )
In the future, I'm going to make it automatic, but i temporarily postponed the development of the project )0))

**Comment by progressionnetwork** [comment]
So we just need to enumerate all functions' addresses and offset to data while disasm?

**Comment by jnastarot** [comment]
Yep, for extract some big function you need get all subfunctions and data regions (offset and size),
subfunctions called from code is now detectable but if call\jmp not direct and address of subfunction hold in data region its not detect on this moment.
Now it can detect only some specific data like "security cookie", "guard call thunk".
